version: "3"

services:

  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: ecommerce
      MYSQL_ROOT_PASSWORD: 1234
      TZ: "Asia/Seoul"
    ports:
      - "3306:3306"
    volumes:
      - ./src/sql/ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
      - ./src/sql/dml.sql:/docker-entrypoint-initdb.d/dml.sql
    networks:
      - network

  spring:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - mysql
    restart: unless-stopped
    environment:
      TZ: "Asia/Seoul"
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ecommerce
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    ports:
      - "8080:8080"
    networks:
      - network


networks:
  network: